export const IS_WRITTER_INSERTED = "IS_WRITTER_INSERTED";
export const IS_BUTTON_LOADER = "IS_BUTTON_LOADER";
export const GET_WRITTER_INPUT = "GET_WRITTER_INPUT";
export const IS_WRITTER_UPDATE = "IS_WRITTER_UPDATE";
export const IS_WRITTER_LOADER = "IS_WRITTER_LOADER";
export const WRITTER_LIST = "WRITTER_LIST";
export const SET_WRITTER_DATA = "SET_WRITTER_DATA";
export const IS_WRITTER_DELETED = "IS_WRITTER_DELETED";
