export const GET_CATEGORY_INPUT = "GET_CATEGORY_INPUT";
export const IS_LOAD_CATEGORY = "IS_LOAD_CATEGORY";
export const IS_SUCCESS_CATEGORY = "IS_SUCCESS_CATEGORY";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const IS_LOAD_CATEGORY_LIST = "IS_LOAD_CATEGORY_LIST";
export const IS_CATEGORY_DELETED = "IS_CATEGORY_DELETED";
export const SET_CATEGORY_UPDATED = "SET_CATEGORY_UPDATED";
