export const IS_CATEGORY_INSERTED = "IS_CATEGORY_INSERTED";
export const IS_BUTTON_LOADER = "IS_BUTTON_LOADER";
export const GET_CATEGORY_INPUT = "GET_CATEGORY_INPUT";
export const IS_CATEGORY_UPDATE = "IS_CATEGORY_UPDATE";
export const IS_CATEGORY_LOADER = "IS_CATEGORY_LOADER";
export const CATEGORY_LIST = "CATEGORY_LIST";
export const SET_CATEGORY_DATA = "SET_CATEGORY_DATA";
export const IS_CATEGORY_DELETED = "IS_CATEGORY_DELETED";
