export const IS_NEWS_INSERTED = "IS_NEWS_INSERTED";
export const IS_BUTTON_LOADER = "IS_BUTTON_LOADER";
export const GET_NEWS_INPUT = "GET_NEWS_INPUT";
export const IS_NEWS_UPDATE = "IS_NEWS_UPDATE";
export const IS_NEWS_LOADER = "IS_NEWS_LOADER";
export const NEWS_LIST = "NEWS_LIST";
export const SET_NEWS_DATA = "SET_NEWS_DATA";
export const IS_NEWS_DELETED = "IS_NEWS_DELETED";
